# Configuration
greetings:
  - "Watch out everyone it is {name}"
  - "Hello, {name}"
  - "Party's over, {name} has joined"
  - "Hi, {name}. I love you"
  - "Ayyy it's {name}, hello"
  - "Welcome to voice chat, {name}"
  - "I was having a great day until {name} joined"
  - "Who just joined? Oh it's {name}"
  - "A cutie named {name} just joined"
  - "Everyone give {name} a vibe check"
  - "Everyone move to the other channel, {name} has joined"
  - "Sad peepos in the chat, {name} is here"
  - "Oh no, look who decided to show up. It's {name}"
  - "Wussup {name}"
  - "Police? Yep. {name} is here. We'll keep them occupied"
  - "Hide your children, it's {name}"
  - "{name} is a national hero and should be treasured"
  - "All hail {name}, our supreme leader"
  - "Hello {name}, we have awaited your arrival"
  - "Hello {name}, here's your complimentary smoothie"
  - "Welcome {name}. The average IQ here just doubled"
  - "Hi {name}, good to see you"
  - "{name}'s ripe this time of year"
  - "The king of skux has arrived. All hail the omnipotent {name}"
  - "It's my birthday and {name} is here as my present"
  - "uwu notices {name}. Someones happy"
