version: "3.3"
services:
  vegebot:
    build: .
    environment:
      DISCORD_TOKEN: ${DISCORD_BOT_TOKEN}
      POSTGREST_TOKEN: ${POSTGREST_TOKEN}
      POSTGREST_URL: http://postgrest:3000
      WEBAPP_URL: ${WEBAPP_URL}
      POSTGRES_HOST: postgres
      POSTGRES_DB: vege_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  pgdata: